### ISSUE TITLE
Use storage_path function for storage files

### ISSUE THREAD

**Issue by giunashvili** [RedberryInternship/gigagiorgadze-laravel-8-from-scratch#59]
https://github.com/RedberryInternship/gigagiorgadze-laravel-8-from-scratch/blob/6460c1b1b2b56da14ef38aa85b223ca237a4aab1/resources/views/posts/show.blade.php#L6

**Comment by GigaGiorgadze** [comment]
![image](https://user-images.githubusercontent.com/75663118/144432346-1e21c7c6-2221-448f-a619-44c2d6dd3bf5.png)

using storage path gives absolute path which browser can't find :/ maybe cuz im using WSL?
